---
namespace: "serdigital64"
name: "hardware"
version: "2.0.0"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating hardware drivers provisioning."
license:
  - "Apache-2.0"
tags:
  - "hardware"
dependencies:
  serdigital64.backup: "*"
  serdigital64.system: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
